---
:initial_population: 100
:initial_infected: 1
:transmission_ratio: 5
:intervention_day: 100
:trans_ratio_reduction: 0.0
:run_length: 100
:report_interval: 1
:outside_infection_meantime: 1000000
:community_testing_meantime: 10
:commun_test_false_negative: 0.04
:commun_test_false_positive: 0.03
:commun_test_duration: 4.0
:alert_test_false_negative: 0.04
:alert_test_false_positive: 0.03
:alert_test_duration: 3.0
:alert_test_plan: y
:alert_test_plan_ideal_delta_t: 3.6
:alert_test_plan_test_interval: 7
:alert_test_plan_max_retests: 1
:alert_test_plan_early_release: y
:prop_asymptomatic: 0.1
:prop_symptomatic_tested: 0.9
:indiv_test_false_negative: 0.04
:indiv_test_false_positive: 0.03
:indiv_test_duration: 3.5
:indiv_test_early_quarantine: y
:commun_test_early_quarantine: n
:trace_test_early_quarantine: y
:mean_contacts: 10
:contact_trace_time: 2
:outside_contact_trace_time: 6
:periodic_reports: n
:intervention_on_duration: 100
:intervention_off_duration: 100
:worksched_on_duration: 5
:worksched_off_duration: 2
:worksched_off_trans_ratio_reduction: -0.15
:q_days: 14
:prob_alert_type0: 0
:prob_commun_type0: 0
:prob_indiv_type0: 0
:indiv_ideal_day: y
